### ISSUE TITLE
无法执行

### ISSUE THREAD

**Issue by Jarvis-K** [EnixCoda/ECNU-policy-exam-on-yiban-server#1]
go.php好像没写完，go.python添加上账号和密码参数也不能执行完成

**Comment by EnixCoda** [comment]
我发布前实测通过go.php进行提交是可以跑通流程的，内部只提供了最基础的功能就是了

如果你是指结尾没有`?>`的话，现在的PHP语法似乎是不建议在尾部写上`?>`的？

另外go.py不能执行完成的具体表现是？

**Comment by EnixCoda** [comment]
你说的不能执行完成可能是跟go.py的123行处理有关，这里有低分取消的机制

**Comment by YijunYuan** [comment]
我这里直接填上账号和密码参数以后py会在31行报错。

**Comment by EnixCoda** [comment]
@YijunYuan 报错的内容是？
